<#
.SYNOPSIS
    IronLogic AI Automation — Master Launcher
.DESCRIPTION
    Reads config/automation_config.json, sets up logging, runs the requested
    agent, and generates a report. Called by Windows Task Scheduler or manually.
.PARAMETER Agent
    Which agent to run: code_review, issue_detection, cleanup
.PARAMETER ConfigPath
    Path to automation_config.json (default: ../config/automation_config.json)
.EXAMPLE
    .\master_launcher.ps1 -Agent code_review
    .\master_launcher.ps1 -Agent issue_detection
#>

param(
    [Parameter(Mandatory = $true)]
    [ValidateSet('code_review', 'issue_detection', 'cleanup')]
    [string]$Agent,

    [string]$ConfigPath = ""
)

# ── Resolve paths ──────────────────────────────────────────────
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Resolve-Path "$ScriptDir\.."

if (-not $ConfigPath) {
    $ConfigPath = "$ProjectRoot\config\automation_config.json"
}

# ── Load config ────────────────────────────────────────────────
if (-not (Test-Path $ConfigPath)) {
    Write-Error "Config not found: $ConfigPath"
    exit 1
}

$config = Get-Content $ConfigPath -Raw | ConvertFrom-Json

# ── Setup logging ──────────────────────────────────────────────
$LogDir = Resolve-Path "$ProjectRoot\$($config.logging.log_dir)"
if (-not (Test-Path $LogDir)) { New-Item -ItemType Directory -Path $LogDir -Force | Out-Null }

$Timestamp = Get-Date -Format "yyyy-MM-dd_HHmmss"
$LogFile = "$LogDir\$Agent`_$Timestamp.log"
$TranscriptFile = "$LogDir\$Agent`_$Timestamp`_transcript.log"

function Write-Log {
    param([string]$Level, [string]$Message)
    $line = "[$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')] [$Level] $Message"
    Add-Content -Path $LogFile -Value $line
    if ($Level -in 'ERROR', 'WARN') {
        Write-Host $line -ForegroundColor ($Level -eq 'ERROR' ? 'Red' : 'Yellow')
    } else {
        Write-Host $line
    }
}

Start-Transcript -Path $TranscriptFile -Append | Out-Null

Write-Log "INFO" "=== Master Launcher started ==="
Write-Log "INFO" "Agent: $Agent"
Write-Log "INFO" "Project root: $ProjectRoot"
Write-Log "INFO" "Config: $ConfigPath"

# ── Validate schedule entry ────────────────────────────────────
$scheduleEntry = $config.schedule.$Agent
if (-not $scheduleEntry) {
    Write-Log "ERROR" "No schedule entry found for agent '$Agent'"
    Stop-Transcript
    exit 1
}

if (-not $scheduleEntry.enabled) {
    Write-Log "INFO" "Agent '$Agent' is disabled in config. Exiting."
    Stop-Transcript
    exit 0
}

# ── Locate and run agent ───────────────────────────────────────
$AgentDir = Resolve-Path "$ProjectRoot\$($config.ai_root)\agents"
$AgentScript = Get-ChildItem "$AgentDir\$Agent.ps1" -ErrorAction SilentlyContinue

if (-not $AgentScript) {
    Write-Log "ERROR" "Agent script not found: $AgentDir\$Agent.ps1"
    Stop-Transcript
    exit 1
}

Write-Log "INFO" "Launching agent: $($AgentScript.FullName)"
$agentResult = & $AgentScript.FullName -ProjectRoot $ProjectRoot -Config $config -LogFile $LogFile 2>&1

if ($LASTEXITCODE -and $LASTEXITCODE -ne 0) {
    Write-Log "ERROR" "Agent exited with code $LASTEXITCODE"
    Write-Log "ERROR" "Output: $agentResult"
} else {
    Write-Log "INFO" "Agent completed successfully"
}

# ── Generate report ────────────────────────────────────────────
$ReportDir = Resolve-Path "$ProjectRoot\$($config.reports.report_dir)"
if (-not (Test-Path $ReportDir)) { New-Item -ItemType Directory -Path $ReportDir -Force | Out-Null }

$WeekNumber = (Get-Date -Format "yyyy-W") + [Math]::Floor((Get-Date).DayOfYear / 7).ToString("00")
$ReportFile = "$ReportDir\$Agent`_$WeekNumber.md"

$reportBody = @"
# $Agent Report — $(Get-Date -Format "yyyy-MM-dd")

**Run**: $Timestamp
**Status**: $($LASTEXITCODE -eq 0 -or -not $LASTEXITCODE ? 'Success' : "Failed (exit code $LASTEXITCODE)")
**Log**: `$LogFile`

## Summary

Agent **$Agent** executed on $(Get-Date -Format "dddd, MMMM dd, yyyy").

## Output

```
$agentResult
```

---
*Generated by IronLogic Automation — $Timestamp*
"@

$reportBody | Out-File -FilePath $ReportFile -Encoding utf8
Write-Log "INFO" "Report written to $ReportFile"

# ── Prune old logs ─────────────────────────────────────────────
$maxDays = [int]$config.logging.max_log_days
if ($maxDays -gt 0) {
    $cutoff = (Get-Date).AddDays(-$maxDays)
    $oldLogs = Get-ChildItem $LogDir -Filter "$Agent*.log" | Where-Object { $_.LastWriteTime -lt $cutoff }
    foreach ($old in $oldLogs) {
        Remove-Item $old.FullName -Force
        Write-Log "INFO" "Pruned old log: $($old.Name)"
    }
}

# ── Prune old reports ──────────────────────────────────────────
$maxReports = [int]$config.reports.max_reports
if ($maxReports -gt 0) {
    $reports = Get-ChildItem $ReportDir -Filter "$Agent*.md" | Sort-Object LastWriteTime -Descending
    if ($reports.Count -gt $maxReports) {
        $toRemove = $reports[$maxReports..($reports.Count - 1)]
        foreach ($r in $toRemove) {
            Remove-Item $r.FullName -Force
            Write-Log "INFO" "Pruned old report: $($r.Name)"
        }
    }
}

Write-Log "INFO" "=== Master Launcher finished ==="
Stop-Transcript
